version: '3.8'
services:
  ms-store:
    container_name: ms-store
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/infrastructure/database/scripts/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - '5432:5432'
    networks:
      - ms-store-network

  ms-store-api:
    container_name: ms-store-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    environment:
      CORS_ORIGIN: "*"
      DATABASE_HOST: "ms-store"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_NAME: "storeSandboxDB"
    ports:
      - '3000:3000'
    depends_on:
      - ms-store
    networks:
      - ms-store-network

  ms-orm:
    container_name: ms-orm
    build:
      context: .
      dockerfile: ./Dockerfile.orm
    environment:
      DATABASE_HOST: "ms-store"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_NAME: "storeSandboxDB"
    ports:
      - '9000:8080'
    networks:
      - ms-store-network
    depends_on:
      - ms-store

volumes:
  postgres:


networks:
  ms-store-network:
    name: MS-STORE
    driver: bridge
