version: '3.8'
services:
  my-project-store:
    container_name: my-project-store
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/infrastructure/database/scripts/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - '5422:5432'

  my-project:
    depends_on:
      - my-project-store
    container_name: my-project
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - '3000:3000'
    environment:
      CORS_ORIGIN: "*"
      DATABASE_HOST: "my-project-store"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_DATABASE: "apiStoreDB"

volumes:
  postgres:


