# hadolint ignore=DL3007
FROM heronlabs/node-alpine:latest

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile \
  && yarn cache clean \
  && yarn compile

EXPOSE 3000

CMD ["yarn", "api:start"]