version: '3.8'
services:
  store:
    container_name: store
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/infrastructure/database/scripts/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - '5422:5432'

  api:
    depends_on:
      - store
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - '3000:3000'
    environment:
      CORS_ORIGIN: "*"
      DATABASE_HOST: "store"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_NAME: "storeSandboxDB"

  orm:
    depends_on:
      - store
    container_name: orm
    build:
      context: .
      dockerfile: ./Dockerfile.orm
    environment:
      DATABASE_HOST: "store"
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_NAME: "storeSandboxDB"

volumes:
  postgres:
