name: Build

on:
  - workflow_dispatch
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[ACTION] | Clone build database action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-database-action
          ref: 3.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
          path: ./build-database-action

      - name: '[ACTION] | Run build database action'
        uses: './build-database-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}

      - name: '[ACTION] | Clone build api action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-api-action
          ref: 3.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
          path: ./build-api-action

      - name: '[ACTION] | Run build api action'
        uses: './build-api-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
