name: Build API Store Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[CONFIG] | TS Node'
        run: npm i -g ts-node
        shell: bash

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-database-action
          ref: 1.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-database-action

      - name: Run action
        uses: './build-database-action/application/github'

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-api-action
          ref: 1.1.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-api-action

      - name: Run action
        uses: './build-api-action/application/github'
